
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class parser/sym {
  /* terminals */
  public static final int COMPARACION = 8;
  public static final int INTEGER = 2;
  public static final int SUMA = 9;
  public static final int L_STRING = 10;
  public static final int EOF = 0;
  public static final int STRING = 3;
  public static final int error = 1;
  public static final int L_INTEGER = 6;
  public static final int IDENTIFICADOR = 5;
  public static final int CHAR = 4;
  public static final int ASIGNA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "STRING",
  "CHAR",
  "IDENTIFICADOR",
  "L_INTEGER",
  "ASIGNA",
  "COMPARACION",
  "SUMA",
  "L_STRING"
  };
}

